CREATE DATABASE IF NOT EXISTS COMP3335;
USE COMP3335;

CREATE TABLE User(
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    pKey VARCHAR(255),
    registerationTime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
)