CREATE DATABASE IF NOT EXISTS COMP3335;
USE COMP3335;

CREATE TABLE IF NOT EXISTS User(
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    shastaKey VARCHAR(255),
    registerationTime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
)

CREATE TABLE IF NOT EXISTS File(
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    ownerID INT NOT NULL,
    hash VARCHAR(255),
    createTime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
    uploadTime DATETIME,
    FOREIGN KEY (ownerID) REFERENCES User(id)
)

CREATE TABLE IF NOT EXISTS Share(
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    fileID INT NOT NULL,
    toUserID INT NOT NULL,
    shareTime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    valid BOOLEAN NOT NULL DEFAULT 1,
    FOREIGN KEY (fileID) REFERENCES File(id),
    FOREIGN KEY (toUSERID) REFERENCES User(id)
)