CREATE DATABASE IF NOT EXISTS COMP3335;

USE COMP3335;

CREATE TABLE IF NOT EXISTS User(
    id INT AUTO_INCREMENT NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    activated BOOLEAN NOT NULL DEFAULT 0,
    activationCode VARCHAR(10) NOT NULL,
    registerationTime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ForgotPassword(
    id INT AUTO_INCREMENT NOT NULL,
    userID INT NOT NULL,
    resetLinkHash VARCHAR(255) NOT NULL,
    valid BOOLEAN NOT NULL DEFAULT 1,
    done BOOLEAN NOT NULL DEFAULT 0,
    requestTime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (userID) REFERENCES User(id)
);

CREATE TABLE IF NOT EXISTS File(
    id INT AUTO_INCREMENT NOT NULL,
    ownerID INT NOT NULL,
    orgName VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    mimeType VARCHAR(255) NOT NULL,
    extension VARCHAR(255) NOT NULL,
    iv VARCHAR(255),
    createTime VARCHAR(255) NOT NULL,
    link VARCHAR(255),
    deleted BOOLEAN NOT NULL DEFAULT 0,
    public BOOLEAN NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    FOREIGN KEY (ownerID) REFERENCES User(id)
);

CREATE TABLE IF NOT EXISTS Share(
    id INT AUTO_INCREMENT NOT NULL,
    ownerID INT NOT NULL,
    fileID INT NOT NULL,
    toUserID INT,
    email VARCHAR(255),
    shareTime DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    hash VARCHAR(255),
    onetime BOOLEAN NOT NULL DEFAULT 0,
    valid BOOLEAN NOT NULL DEFAULT 1,
    PRIMARY KEY (id),
    FOREIGN KEY (fileID) REFERENCES File(id),
    FOREIGN KEY (toUSERID) REFERENCES User(id),
    FOREIGN KEY (ownerID) REFERENCES User(id)
);